apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  annotations:
    manifestival: new
  name: nodejs-healthcheck-test-pl
  namespace: kabanero
spec:
  params:
    - description: The event type
      name: event-type
      type: string
    - description: The event ref
      name: event-ref
      type: string
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: health-check
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      taskRef:
        kind: Task
        name: health-check-task
